// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Wing.SqlServer.Migrations
{
    [DbContext(typeof(GateWayDbContext))]
    [Migration("20220227143250_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wing.Models.GateWay.Log", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ClientIp")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DownstreamUrl")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Policy")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("RequestTime")
                        .HasColumnType("datetime");

                    b.Property<string>("RequestType")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RequestUrl")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RequestValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResponseTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ResponseValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("varchar(800)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GateWay_Log");
                });
#pragma warning restore 612, 618
        }
    }
}
